---
title: "Święty Piotr jest większym filozofem od Platona"
description: "Kazanie świętego Jana Chryzostoma, w którym argumentuje, dlaczego święty Piotr jest większym filozofem niż Platon"
---

# Komentarz do Dziejów Apostolskich, Homilia 4[^1]



[...] Czyż oni (apostołowie) nie walczyli z ubóstwem i głodem, z hańbą i niesławą (gdyż uważano ich za oszustów), czyż nie walczyli z drwinami, gniewem i szyderstwem? – w ich przypadku spotykały się bowiem przeciwieństwa: jedni się z nich śmiali, inni ich karali – czyż nie stali się oni obiektem gniewnych namiętności i rozrywki całych miast? Czy nie byli narażeni na spory i spiski, na ogień, miecz i dzikie zwierzęta? Czyż nie otaczała ich wojna ze wszystkich stron, przybierając dziesięć tysięcy postaci? Czyż wszystkie te rzeczy miały na nich większy wpływ niż widok tych rzeczy we śnie lub na obrazie? Z gołym ciałem stanęli do walki przeciwko wszystkim uzbrojonym, choć wszyscy mieli nad nimi władzę [przeciwko nim]: strach przed władcami, siła broni, miasta i mocne mury: bez doświadczenia, bez umiejętności językowych, w stanie zupełnie zwykłych ludzi, zmierzyli się z magikami, oszustami, całym tłumem sofistów, retoryków, filozofów zardzewiałych w Akademii i na spacerach perypatetyków, przeciwko wszystkim tym stoczyli walkę. A człowiek, którego zajęciem były jeziora, tak ich opanował, jakby nie kosztowało go to więcej wysiłku niż walka z niemymi rybami: tak jakby przeciwnicy, których musiał przechytrzyć, byli rzeczywiście bardziej niemi niż ryby, tak łatwo ich pokonał! A Platon, który za swego życia wygłaszał wiele bzdur, milczy teraz, podczas gdy ten człowiek głosi swoje nauki wszędzie; nie tylko wśród swoich rodaków, ale także wśród Partów, Medów, Elamitów, w Indiach i we wszystkich częściach świata, aż po krańce ziemi. Gdzie jest teraz Grecja z jej wielkimi pretensjami? Gdzie imię Aten? Gdzie są brednie filozofów? Ten z Galilei, ten z Betsaidy, ten nieokrzesany wieśniak, pokonał ich wszystkich. Czy nie wstydzicie się – przyznajcie to – samego imienia kraju, który was pokonał? Ale jeśli usłyszycie jego imię i dowiecie się, że nazywał się Kefas, tym bardziej ukryjecie swoje twarze. Nie podążaliście drogą, którą powinniście byli wybrać, ale opuściliście drogę królewską, tak łatwą i gładką, i wkroczyliście na drogę trudną, stromą i mozolną. Dlatego nie osiągnęliście królestwa niebieskiego. 

Dlaczego więc, pyta się, Chrystus nie wywarł wpływu na Platona i Pitagorasa? Ponieważ umysł Piotra był znacznie bardziej filozoficzny niż ich umysły. Oni byli w rzeczywistości dziećmi miotanymi na wszystkie strony przez próżną chwałę, ale ten człowiek był filozofem, zdolnym do przyjęcia łaski. Jeśli śmiejecie się z tych słów, nie ma w tym nic dziwnego, ponieważ dawniej śmiali się i mówili, że ci ludzie są pełni młodego wina. Ale potem, kiedy doświadczyli gorzkich nieszczęść, przewyższających wszystkie inne w nędzy, kiedy zobaczyli swoje miasto w ruinie, płonące w ogniu, zburzone mury i te liczne szalone okropności, których nikt nie potrafi opisać słowami, wtedy nie śmiali się. A wy będziecie się śmiać, jeśli będziecie mieli na to ochotę, kiedy zbliży się czas piekła, kiedy ogień zostanie rozpalony dla waszych dusz. Ale po co mówię o przyszłości? Czy mam wam pokazać, kim jest Piotr i kim jest filozof Platon? Przyjrzyjmy się na razie ich zwyczajom, zobaczmy, czym się zajmowali. Jeden marnował czas na zbiór bezsensownych i bezużytecznych dogmatów, jak sam twierdzi, filozoficznych, abyśmy mogli dowiedzieć się, że dusza naszego filozofa staje się muchą. Najprawdziwsza prawda, mucha! Nie zmienił się wprawdzie w muchę, ale mucha musiała opanować duszę, która mieszkała w Platonie, bo cóż innego jak mucha jest godna takich idei! Człowiek ten był pełen ironii i zazdrości wobec wszystkich innych, jakby jego ambicją było nie wprowadzać niczego pożytecznego, ani z własnej głowy, ani z głowy innych. W ten sposób przejął od innego metempsychozę, a sam stworzył Republikę, w której ustanowił prawa pełne rażącej niegodziwości. Niech kobiety będą wspólne, niech dziewice chodzą nago i niech walczą na oczach swoich kochanków, niech będą też wspólni ojcowie, a zrodzone dzieci niech będą wspólne. Ale u nas to nie natura sprawia, że ojcowie są wspólni, lecz filozofia Piotra; ta pierwsza bowiem zniosła wszelkie ojcostwo. System Platona dążył jedynie do tego, by prawdziwy ojciec stał się niemal nieznany, a wprowadził fałszywego. Pogrążył duszę w rodzaj upojenia i plugawego tarzania się. Niech wszyscy, mówi, bez strachu obcują z kobietami. Powodem, dla którego nie analizuję maksym poetów, jest to, że nie chcę być oskarżony o rozdzieranie bajek. A jednak mówię o bajkach znacznie bardziej absurdalnych niż te. Gdzie poeci wymyślili coś tak groźnego jak to? Ale (nie wchodząc w dyskusję na temat innych jego maksym), co powiesz na to, że wyposaża kobiety w broń, hełmy i nagolenniki i twierdzi, że rasa ludzka nie ma powodu, by różnić się od psów! Ponieważ, jak twierdzi, suki i psy robią dokładnie to samo, niech kobiety wykonują tę samą pracę co mężczyźni i niech wszystko zostanie wywrócone do góry nogami. Diabeł zawsze starał się bowiem za ich pośrednictwem pokazać, że nasza rasa nie jest bardziej szlachetna od zwierząt, a niektórzy posunęli się nawet do tak absurdalnego twierdzenia, że istoty nierozumne są obdarzone rozumem. Zobaczcie, na ile różnych sposobów rozszalał się on w umysłach tych ludzi! Podczas gdy bowiem ich przywódcy twierdzili, że nasza dusza przechodzi w muchy, psy i zwierzęta, ci, którzy przyszli po nich, wstydząc się tego, popadli w inny rodzaj nikczemności i obdarzyli zwierzęta wszelką racjonalną wiedzą, twierdząc, że stworzenia, które zostały powołane do istnienia dla nas, są pod każdym względem bardziej szlachetne od nas! Przypisują im nawet przewidywanie przyszłości i pobożność. Mówią, że kruk zna Boga, podobnie jak kruki, i że posiadają dar proroctwa i przepowiadają przyszłość; panuje wśród nich sprawiedliwość, porządek i prawo. Być może nie wierzycie w to, co mówię. I słusznie, wychowani jak jesteście na zdrowej doktrynie; gdyby bowiem ktoś był karmiony taką strawą, nigdy nie uwierzyłby, że istnieje człowiek, który czerpie przyjemność z jedzenia odchodów. Według Platona, wśród nich zazdrosny jest również pies. Ale kiedy mówimy im, że są to bajki i pełne absurdalności, odpowiadają: „Nie rozumiecie głębszego znaczenia”. Nie, nie rozumiemy waszych niezrozumiałych bzdur i obyśmy nigdy nie zrozumieli, ponieważ potrzeba (oczywiście!) niezwykle głębokiego umysłu, aby wyjaśnić mi, co oznacza cała ta bezbożność i zamieszanie. Czy wy, bezrozumni ludzie, mówicie językiem kruków, jak to robią dzieci (w zabawie)? Bo wy jesteście naprawdę dziećmi, tak jak one. Ale Piotr nigdy nie pomyślał o wypowiedzeniu tych słów: wydał głos jak wielkie światło świecące w ciemności, głos, który rozproszył mgłę i ciemność całego świata. Ponownie, jego zachowanie, jakże łagodne, jakże rozważne; jakże dalekie od wszelkiej próżności; jak patrzył ku niebu bez wszelkiej pychy, i to nawet podczas wskrzeszania umarłych! Gdyby jednak ktokolwiek z tych bezrozumnych ludzi (oczywiście w czystej fantazji) miał moc uczynić coś podobnego, czyż nie szukałby natychmiast ołtarza i świątyni, które by mu wzniesiono, i nie chciałby być równy bogom? Skoro bowiem nie ma takiego znaku, zawsze oddają się takim fantastycznym wyobrażeniom. A kimże, proszę was, jest ta ich Minerva, Apollo i Juno? Są to różne rodzaje demonów. Mają też swojego króla, który uważa za słuszne umrzeć tylko po to, aby zostać uznanym za równego bogom. Ale nie tak jest tutaj: wręcz przeciwnie. Posłuchajcie, jak mówią przy okazji uzdrowienia chromego. Wy, ludzie Izraela, dlaczego patrzycie na nas tak uważnie, jakbyśmy to naszą własną mocą lub świętością sprawili, że on chodzi? My też jesteśmy ludźmi o takich samych namiętnościach jak wy. Ale u nich wielka jest pycha, wielka przechwałka; wszystko dla ludzkiej chwały, nic dla czystej miłości prawdy i cnoty. Bo gdzie czyn jest wykonywany dla chwały, wszystko jest bezwartościowe. Bo choćby człowiek posiadał wszystko, ale nie panuje nad tym (pożądaniem), traci wszelkie prawo do prawdziwej filozofii, jest niewolnikiem bardziej tyranicznej i haniebnej namiętności. Pogarda dla chwały – to wystarczy, aby nauczyć wszystkiego, co dobre, i wygnać z duszy wszelkie zgubne namiętności. Zachęcam was zatem, abyście dołożyli wszelkich starań, aby wykorzenić tę namiętność; tylko w ten sposób zyskacie uznanie Boga i przyciągniecie do siebie życzliwe spojrzenie Oka, które nigdy nie zasypia. Dlatego też starajmy się z całą gorliwością osiągnąć radość z tego niebiańskiego wpływu, abyśmy w ten sposób uniknęli próby obecnych zła i osiągnęli przyszłe błogosławieństwa dzięki łasce i miłosierdziu naszego Pana Jezusa Chrystusa, któremu wraz z Ojcem i Duchem Świętym niech będzie chwała, moc i cześć teraz i na wieki wieków. Amen.

[^1]: Przetłumaczone z: J. Walker, J. Sheppard and H. Browne, and revised by George B. Stevens. From Nicene and Post-Nicene Fathers, First Series, Vol. 11. Edited by Philip Schaff. (Buffalo, NY: Christian Literature Publishing Co., 1889.) Revised and edited for New Advent by Kevin Knight. <http://www.newadvent.org/fathers/210104.htm>.


{{< include info.txt >}}